package com.ec.entity;

public class Event {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column event.event_Id
     *
     * @mbggenerated Sun Mar 04 22:53:42 CST 2018
     */
    private Integer eventId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column event.event_Title
     *
     * @mbggenerated Sun Mar 04 22:53:42 CST 2018
     */
    private String eventTitle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column event.event_description
     *
     * @mbggenerated Sun Mar 04 22:53:42 CST 2018
     */
    private String eventDescription;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column event.creator_Name
     *
     * @mbggenerated Sun Mar 04 22:53:42 CST 2018
     */
    private String creatorName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column event.project_id
     *
     * @mbggenerated Sun Mar 04 22:53:42 CST 2018
     */
    private Integer projectId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column event.event_Id
     *
     * @return the value of event.event_Id
     *
     * @mbggenerated Sun Mar 04 22:53:42 CST 2018
     */
    public Integer getEventId() {
        return eventId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column event.event_Id
     *
     * @param eventId the value for event.event_Id
     *
     * @mbggenerated Sun Mar 04 22:53:42 CST 2018
     */
    public void setEventId(Integer eventId) {
        this.eventId = eventId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column event.event_Title
     *
     * @return the value of event.event_Title
     *
     * @mbggenerated Sun Mar 04 22:53:42 CST 2018
     */
    public String getEventTitle() {
        return eventTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column event.event_Title
     *
     * @param eventTitle the value for event.event_Title
     *
     * @mbggenerated Sun Mar 04 22:53:42 CST 2018
     */
    public void setEventTitle(String eventTitle) {
        this.eventTitle = eventTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column event.event_description
     *
     * @return the value of event.event_description
     *
     * @mbggenerated Sun Mar 04 22:53:42 CST 2018
     */
    public String getEventDescription() {
        return eventDescription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column event.event_description
     *
     * @param eventDescription the value for event.event_description
     *
     * @mbggenerated Sun Mar 04 22:53:42 CST 2018
     */
    public void setEventDescription(String eventDescription) {
        this.eventDescription = eventDescription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column event.creator_Name
     *
     * @return the value of event.creator_Name
     *
     * @mbggenerated Sun Mar 04 22:53:42 CST 2018
     */
    public String getCreatorName() {
        return creatorName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column event.creator_Name
     *
     * @param creatorName the value for event.creator_Name
     *
     * @mbggenerated Sun Mar 04 22:53:42 CST 2018
     */
    public void setCreatorName(String creatorName) {
        this.creatorName = creatorName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column event.project_id
     *
     * @return the value of event.project_id
     *
     * @mbggenerated Sun Mar 04 22:53:42 CST 2018
     */
    public Integer getProjectId() {
        return projectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column event.project_id
     *
     * @param projectId the value for event.project_id
     *
     * @mbggenerated Sun Mar 04 22:53:42 CST 2018
     */
    public void setProjectId(Integer projectId) {
        this.projectId = projectId;
    }
}