package com.ec.entity;

public class Instructor {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column instructor.Instructor_id
     *
     * @mbggenerated Sun Mar 04 21:46:52 CST 2018
     */
    private Integer instructorId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column instructor.Name
     *
     * @mbggenerated Sun Mar 04 21:46:52 CST 2018
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column instructor.Password
     *
     * @mbggenerated Sun Mar 04 21:46:52 CST 2018
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column instructor.Email_add
     *
     * @mbggenerated Sun Mar 04 21:46:52 CST 2018
     */
    private String emailAdd;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column instructor.Instructor_id
     *
     * @return the value of instructor.Instructor_id
     *
     * @mbggenerated Sun Mar 04 21:46:52 CST 2018
     */
    public Integer getInstructorId() {
        return instructorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column instructor.Instructor_id
     *
     * @param instructorId the value for instructor.Instructor_id
     *
     * @mbggenerated Sun Mar 04 21:46:52 CST 2018
     */
    public void setInstructorId(Integer instructorId) {
        this.instructorId = instructorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column instructor.Name
     *
     * @return the value of instructor.Name
     *
     * @mbggenerated Sun Mar 04 21:46:52 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column instructor.Name
     *
     * @param name the value for instructor.Name
     *
     * @mbggenerated Sun Mar 04 21:46:52 CST 2018
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column instructor.Password
     *
     * @return the value of instructor.Password
     *
     * @mbggenerated Sun Mar 04 21:46:52 CST 2018
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column instructor.Password
     *
     * @param password the value for instructor.Password
     *
     * @mbggenerated Sun Mar 04 21:46:52 CST 2018
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column instructor.Email_add
     *
     * @return the value of instructor.Email_add
     *
     * @mbggenerated Sun Mar 04 21:46:52 CST 2018
     */
    public String getEmailAdd() {
        return emailAdd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column instructor.Email_add
     *
     * @param emailAdd the value for instructor.Email_add
     *
     * @mbggenerated Sun Mar 04 21:46:52 CST 2018
     */
    public void setEmailAdd(String emailAdd) {
        this.emailAdd = emailAdd;
    }
}