package com.ec.entity;

import java.util.Date;

public class Message {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.message_Id
     *
     * @mbggenerated Mon Mar 05 17:00:05 CST 2018
     */
    private Integer messageId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.project_Id
     *
     * @mbggenerated Mon Mar 05 17:00:05 CST 2018
     */
    private Integer projectId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.senderName
     *
     * @mbggenerated Mon Mar 05 17:00:05 CST 2018
     */
    private String sendername;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.time
     *
     * @mbggenerated Mon Mar 05 17:00:05 CST 2018
     */
    private Date time;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.content
     *
     * @mbggenerated Mon Mar 05 17:00:05 CST 2018
     */
    private String content;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.message_Id
     *
     * @return the value of message.message_Id
     *
     * @mbggenerated Mon Mar 05 17:00:05 CST 2018
     */
    public Integer getMessageId() {
        return messageId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.message_Id
     *
     * @param messageId the value for message.message_Id
     *
     * @mbggenerated Mon Mar 05 17:00:05 CST 2018
     */
    public void setMessageId(Integer messageId) {
        this.messageId = messageId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.project_Id
     *
     * @return the value of message.project_Id
     *
     * @mbggenerated Mon Mar 05 17:00:05 CST 2018
     */
    public Integer getProjectId() {
        return projectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.project_Id
     *
     * @param projectId the value for message.project_Id
     *
     * @mbggenerated Mon Mar 05 17:00:05 CST 2018
     */
    public void setProjectId(Integer projectId) {
        this.projectId = projectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.senderName
     *
     * @return the value of message.senderName
     *
     * @mbggenerated Mon Mar 05 17:00:05 CST 2018
     */
    public String getSendername() {
        return sendername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.senderName
     *
     * @param sendername the value for message.senderName
     *
     * @mbggenerated Mon Mar 05 17:00:05 CST 2018
     */
    public void setSendername(String sendername) {
        this.sendername = sendername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.time
     *
     * @return the value of message.time
     *
     * @mbggenerated Mon Mar 05 17:00:05 CST 2018
     */
    public Date getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.time
     *
     * @param time the value for message.time
     *
     * @mbggenerated Mon Mar 05 17:00:05 CST 2018
     */
    public void setTime(Date time) {
        this.time = time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.content
     *
     * @return the value of message.content
     *
     * @mbggenerated Mon Mar 05 17:00:05 CST 2018
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.content
     *
     * @param content the value for message.content
     *
     * @mbggenerated Mon Mar 05 17:00:05 CST 2018
     */
    public void setContent(String content) {
        this.content = content;
    }
}