package com.ec.entity;

import java.util.Date;

public class Participate extends ParticipateKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column participate.Participate_Time
     *
     * @mbggenerated Sun Mar 04 22:53:42 CST 2018
     */
    private Date participateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column participate.Role
     *
     * @mbggenerated Sun Mar 04 22:53:42 CST 2018
     */
    private Integer role;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column participate.Contribution
     *
     * @mbggenerated Sun Mar 04 22:53:42 CST 2018
     */
    private Integer contribution;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column participate.Participate_Time
     *
     * @return the value of participate.Participate_Time
     *
     * @mbggenerated Sun Mar 04 22:53:42 CST 2018
     */
    public Date getParticipateTime() {
        return participateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column participate.Participate_Time
     *
     * @param participateTime the value for participate.Participate_Time
     *
     * @mbggenerated Sun Mar 04 22:53:42 CST 2018
     */
    public void setParticipateTime(Date participateTime) {
        this.participateTime = participateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column participate.Role
     *
     * @return the value of participate.Role
     *
     * @mbggenerated Sun Mar 04 22:53:42 CST 2018
     */
    public Integer getRole() {
        return role;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column participate.Role
     *
     * @param role the value for participate.Role
     *
     * @mbggenerated Sun Mar 04 22:53:42 CST 2018
     */
    public void setRole(Integer role) {
        this.role = role;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column participate.Contribution
     *
     * @return the value of participate.Contribution
     *
     * @mbggenerated Sun Mar 04 22:53:42 CST 2018
     */
    public Integer getContribution() {
        return contribution;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column participate.Contribution
     *
     * @param contribution the value for participate.Contribution
     *
     * @mbggenerated Sun Mar 04 22:53:42 CST 2018
     */
    public void setContribution(Integer contribution) {
        this.contribution = contribution;
    }
}