package com.ec.entity;

public class ParticipateKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column participate.Project_id
     *
     * @mbggenerated Sun Mar 04 21:46:52 CST 2018
     */
    private Integer projectId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column participate.Student_id
     *
     * @mbggenerated Sun Mar 04 21:46:52 CST 2018
     */
    private Integer studentId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column participate.Project_id
     *
     * @return the value of participate.Project_id
     *
     * @mbggenerated Sun Mar 04 21:46:52 CST 2018
     */
    public Integer getProjectId() {
        return projectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column participate.Project_id
     *
     * @param projectId the value for participate.Project_id
     *
     * @mbggenerated Sun Mar 04 21:46:52 CST 2018
     */
    public void setProjectId(Integer projectId) {
        this.projectId = projectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column participate.Student_id
     *
     * @return the value of participate.Student_id
     *
     * @mbggenerated Sun Mar 04 21:46:52 CST 2018
     */
    public Integer getStudentId() {
        return studentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column participate.Student_id
     *
     * @param studentId the value for participate.Student_id
     *
     * @mbggenerated Sun Mar 04 21:46:52 CST 2018
     */
    public void setStudentId(Integer studentId) {
        this.studentId = studentId;
    }
}