package com.ec.entity;

import java.util.Date;

public class Phase {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column phase.Phase_id
     *
     * @mbggenerated Sun Mar 04 21:46:52 CST 2018
     */
    private Integer phaseId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column phase.Project_id
     *
     * @mbggenerated Sun Mar 04 21:46:52 CST 2018
     */
    private Integer projectId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column phase.Ph_begin_time
     *
     * @mbggenerated Sun Mar 04 21:46:52 CST 2018
     */
    private Date phBeginTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column phase.Ph_end_time
     *
     * @mbggenerated Sun Mar 04 21:46:52 CST 2018
     */
    private Date phEndTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column phase.Ph_title
     *
     * @mbggenerated Sun Mar 04 21:46:52 CST 2018
     */
    private String phTitle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column phase.Ph_description
     *
     * @mbggenerated Sun Mar 04 21:46:52 CST 2018
     */
    private String phDescription;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column phase.Phase_id
     *
     * @return the value of phase.Phase_id
     *
     * @mbggenerated Sun Mar 04 21:46:52 CST 2018
     */
    public Integer getPhaseId() {
        return phaseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column phase.Phase_id
     *
     * @param phaseId the value for phase.Phase_id
     *
     * @mbggenerated Sun Mar 04 21:46:52 CST 2018
     */
    public void setPhaseId(Integer phaseId) {
        this.phaseId = phaseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column phase.Project_id
     *
     * @return the value of phase.Project_id
     *
     * @mbggenerated Sun Mar 04 21:46:52 CST 2018
     */
    public Integer getProjectId() {
        return projectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column phase.Project_id
     *
     * @param projectId the value for phase.Project_id
     *
     * @mbggenerated Sun Mar 04 21:46:52 CST 2018
     */
    public void setProjectId(Integer projectId) {
        this.projectId = projectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column phase.Ph_begin_time
     *
     * @return the value of phase.Ph_begin_time
     *
     * @mbggenerated Sun Mar 04 21:46:52 CST 2018
     */
    public Date getPhBeginTime() {
        return phBeginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column phase.Ph_begin_time
     *
     * @param phBeginTime the value for phase.Ph_begin_time
     *
     * @mbggenerated Sun Mar 04 21:46:52 CST 2018
     */
    public void setPhBeginTime(Date phBeginTime) {
        this.phBeginTime = phBeginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column phase.Ph_end_time
     *
     * @return the value of phase.Ph_end_time
     *
     * @mbggenerated Sun Mar 04 21:46:52 CST 2018
     */
    public Date getPhEndTime() {
        return phEndTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column phase.Ph_end_time
     *
     * @param phEndTime the value for phase.Ph_end_time
     *
     * @mbggenerated Sun Mar 04 21:46:52 CST 2018
     */
    public void setPhEndTime(Date phEndTime) {
        this.phEndTime = phEndTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column phase.Ph_title
     *
     * @return the value of phase.Ph_title
     *
     * @mbggenerated Sun Mar 04 21:46:52 CST 2018
     */
    public String getPhTitle() {
        return phTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column phase.Ph_title
     *
     * @param phTitle the value for phase.Ph_title
     *
     * @mbggenerated Sun Mar 04 21:46:52 CST 2018
     */
    public void setPhTitle(String phTitle) {
        this.phTitle = phTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column phase.Ph_description
     *
     * @return the value of phase.Ph_description
     *
     * @mbggenerated Sun Mar 04 21:46:52 CST 2018
     */
    public String getPhDescription() {
        return phDescription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column phase.Ph_description
     *
     * @param phDescription the value for phase.Ph_description
     *
     * @mbggenerated Sun Mar 04 21:46:52 CST 2018
     */
    public void setPhDescription(String phDescription) {
        this.phDescription = phDescription;
    }
}