package com.ec.entity;

import java.util.Date;

public class Project {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.Project_id
     *
     * @mbggenerated Sun Mar 04 18:54:24 CST 2018
     */
    private Integer projectId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.Instructor_id
     *
     * @mbggenerated Sun Mar 04 18:54:24 CST 2018
     */
    private Integer instructorId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.P_begin_time
     *
     * @mbggenerated Sun Mar 04 18:54:24 CST 2018
     */
    private Date pBeginTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.P_end_time
     *
     * @mbggenerated Sun Mar 04 18:54:24 CST 2018
     */
    private Date pEndTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.Grade
     *
     * @mbggenerated Sun Mar 04 18:54:24 CST 2018
     */
    private Float grade;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.P_title
     *
     * @mbggenerated Sun Mar 04 18:54:24 CST 2018
     */
    private String pTitle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.P_description
     *
     * @mbggenerated Sun Mar 04 18:54:24 CST 2018
     */
    private String pDescription;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project.Project_id
     *
     * @return the value of project.Project_id
     *
     * @mbggenerated Sun Mar 04 18:54:24 CST 2018
     */
    public Integer getProjectId() {
        return projectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project.Project_id
     *
     * @param projectId the value for project.Project_id
     *
     * @mbggenerated Sun Mar 04 18:54:24 CST 2018
     */
    public void setProjectId(Integer projectId) {
        this.projectId = projectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project.Instructor_id
     *
     * @return the value of project.Instructor_id
     *
     * @mbggenerated Sun Mar 04 18:54:24 CST 2018
     */
    public Integer getInstructorId() {
        return instructorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project.Instructor_id
     *
     * @param instructorId the value for project.Instructor_id
     *
     * @mbggenerated Sun Mar 04 18:54:24 CST 2018
     */
    public void setInstructorId(Integer instructorId) {
        this.instructorId = instructorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project.P_begin_time
     *
     * @return the value of project.P_begin_time
     *
     * @mbggenerated Sun Mar 04 18:54:24 CST 2018
     */
    public Date getpBeginTime() {
        return pBeginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project.P_begin_time
     *
     * @param pBeginTime the value for project.P_begin_time
     *
     * @mbggenerated Sun Mar 04 18:54:24 CST 2018
     */
    public void setpBeginTime(Date pBeginTime) {
        this.pBeginTime = pBeginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project.P_end_time
     *
     * @return the value of project.P_end_time
     *
     * @mbggenerated Sun Mar 04 18:54:24 CST 2018
     */
    public Date getpEndTime() {
        return pEndTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project.P_end_time
     *
     * @param pEndTime the value for project.P_end_time
     *
     * @mbggenerated Sun Mar 04 18:54:24 CST 2018
     */
    public void setpEndTime(Date pEndTime) {
        this.pEndTime = pEndTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project.Grade
     *
     * @return the value of project.Grade
     *
     * @mbggenerated Sun Mar 04 18:54:24 CST 2018
     */
    public Float getGrade() {
        return grade;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project.Grade
     *
     * @param grade the value for project.Grade
     *
     * @mbggenerated Sun Mar 04 18:54:24 CST 2018
     */
    public void setGrade(Float grade) {
        this.grade = grade;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project.P_title
     *
     * @return the value of project.P_title
     *
     * @mbggenerated Sun Mar 04 18:54:24 CST 2018
     */
    public String getpTitle() {
        return pTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project.P_title
     *
     * @param pTitle the value for project.P_title
     *
     * @mbggenerated Sun Mar 04 18:54:24 CST 2018
     */
    public void setpTitle(String pTitle) {
        this.pTitle = pTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project.P_description
     *
     * @return the value of project.P_description
     *
     * @mbggenerated Sun Mar 04 18:54:24 CST 2018
     */
    public String getpDescription() {
        return pDescription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project.P_description
     *
     * @param pDescription the value for project.P_description
     *
     * @mbggenerated Sun Mar 04 18:54:24 CST 2018
     */
    public void setpDescription(String pDescription) {
        this.pDescription = pDescription;
    }
}