package com.ec.entity;

import java.util.Date;

public class Projectfile {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column projectfile.File_id
     *
     * @mbggenerated Mon Mar 05 17:00:05 CST 2018
     */
    private Integer fileId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column projectfile.Project_id
     *
     * @mbggenerated Mon Mar 05 17:00:05 CST 2018
     */
    private Integer projectId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column projectfile.File_Title
     *
     * @mbggenerated Mon Mar 05 17:00:05 CST 2018
     */
    private String fileTitle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column projectfile.File_URL
     *
     * @mbggenerated Mon Mar 05 17:00:05 CST 2018
     */
    private String fileUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column projectfile.Uploader_id
     *
     * @mbggenerated Mon Mar 05 17:00:05 CST 2018
     */
    private Integer uploaderId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column projectfile.Uploader_Name
     *
     * @mbggenerated Mon Mar 05 17:00:05 CST 2018
     */
    private String uploaderName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column projectfile.Upload_Time
     *
     * @mbggenerated Mon Mar 05 17:00:05 CST 2018
     */
    private Date uploadTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column projectfile.File_id
     *
     * @return the value of projectfile.File_id
     *
     * @mbggenerated Mon Mar 05 17:00:05 CST 2018
     */
    public Integer getFileId() {
        return fileId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column projectfile.File_id
     *
     * @param fileId the value for projectfile.File_id
     *
     * @mbggenerated Mon Mar 05 17:00:05 CST 2018
     */
    public void setFileId(Integer fileId) {
        this.fileId = fileId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column projectfile.Project_id
     *
     * @return the value of projectfile.Project_id
     *
     * @mbggenerated Mon Mar 05 17:00:05 CST 2018
     */
    public Integer getProjectId() {
        return projectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column projectfile.Project_id
     *
     * @param projectId the value for projectfile.Project_id
     *
     * @mbggenerated Mon Mar 05 17:00:05 CST 2018
     */
    public void setProjectId(Integer projectId) {
        this.projectId = projectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column projectfile.File_Title
     *
     * @return the value of projectfile.File_Title
     *
     * @mbggenerated Mon Mar 05 17:00:05 CST 2018
     */
    public String getFileTitle() {
        return fileTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column projectfile.File_Title
     *
     * @param fileTitle the value for projectfile.File_Title
     *
     * @mbggenerated Mon Mar 05 17:00:05 CST 2018
     */
    public void setFileTitle(String fileTitle) {
        this.fileTitle = fileTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column projectfile.File_URL
     *
     * @return the value of projectfile.File_URL
     *
     * @mbggenerated Mon Mar 05 17:00:05 CST 2018
     */
    public String getFileUrl() {
        return fileUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column projectfile.File_URL
     *
     * @param fileUrl the value for projectfile.File_URL
     *
     * @mbggenerated Mon Mar 05 17:00:05 CST 2018
     */
    public void setFileUrl(String fileUrl) {
        this.fileUrl = fileUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column projectfile.Uploader_id
     *
     * @return the value of projectfile.Uploader_id
     *
     * @mbggenerated Mon Mar 05 17:00:05 CST 2018
     */
    public Integer getUploaderId() {
        return uploaderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column projectfile.Uploader_id
     *
     * @param uploaderId the value for projectfile.Uploader_id
     *
     * @mbggenerated Mon Mar 05 17:00:05 CST 2018
     */
    public void setUploaderId(Integer uploaderId) {
        this.uploaderId = uploaderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column projectfile.Uploader_Name
     *
     * @return the value of projectfile.Uploader_Name
     *
     * @mbggenerated Mon Mar 05 17:00:05 CST 2018
     */
    public String getUploaderName() {
        return uploaderName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column projectfile.Uploader_Name
     *
     * @param uploaderName the value for projectfile.Uploader_Name
     *
     * @mbggenerated Mon Mar 05 17:00:05 CST 2018
     */
    public void setUploaderName(String uploaderName) {
        this.uploaderName = uploaderName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column projectfile.Upload_Time
     *
     * @return the value of projectfile.Upload_Time
     *
     * @mbggenerated Mon Mar 05 17:00:05 CST 2018
     */
    public Date getUploadTime() {
        return uploadTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column projectfile.Upload_Time
     *
     * @param uploadTime the value for projectfile.Upload_Time
     *
     * @mbggenerated Mon Mar 05 17:00:05 CST 2018
     */
    public void setUploadTime(Date uploadTime) {
        this.uploadTime = uploadTime;
    }
}