package com.ec.entity;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class ProjectExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table project
     *
     * @mbggenerated Mon Mar 05 16:40:23 CST 2018
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table project
     *
     * @mbggenerated Mon Mar 05 16:40:23 CST 2018
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table project
     *
     * @mbggenerated Mon Mar 05 16:40:23 CST 2018
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project
     *
     * @mbggenerated Mon Mar 05 16:40:23 CST 2018
     */
    public ProjectExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project
     *
     * @mbggenerated Mon Mar 05 16:40:23 CST 2018
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project
     *
     * @mbggenerated Mon Mar 05 16:40:23 CST 2018
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project
     *
     * @mbggenerated Mon Mar 05 16:40:23 CST 2018
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project
     *
     * @mbggenerated Mon Mar 05 16:40:23 CST 2018
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project
     *
     * @mbggenerated Mon Mar 05 16:40:23 CST 2018
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project
     *
     * @mbggenerated Mon Mar 05 16:40:23 CST 2018
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project
     *
     * @mbggenerated Mon Mar 05 16:40:23 CST 2018
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project
     *
     * @mbggenerated Mon Mar 05 16:40:23 CST 2018
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project
     *
     * @mbggenerated Mon Mar 05 16:40:23 CST 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project
     *
     * @mbggenerated Mon Mar 05 16:40:23 CST 2018
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table project
     *
     * @mbggenerated Mon Mar 05 16:40:23 CST 2018
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andProjectIdIsNull() {
            addCriterion("Project_id is null");
            return (Criteria) this;
        }

        public Criteria andProjectIdIsNotNull() {
            addCriterion("Project_id is not null");
            return (Criteria) this;
        }

        public Criteria andProjectIdEqualTo(Integer value) {
            addCriterion("Project_id =", value, "projectId");
            return (Criteria) this;
        }

        public Criteria andProjectIdNotEqualTo(Integer value) {
            addCriterion("Project_id <>", value, "projectId");
            return (Criteria) this;
        }

        public Criteria andProjectIdGreaterThan(Integer value) {
            addCriterion("Project_id >", value, "projectId");
            return (Criteria) this;
        }

        public Criteria andProjectIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("Project_id >=", value, "projectId");
            return (Criteria) this;
        }

        public Criteria andProjectIdLessThan(Integer value) {
            addCriterion("Project_id <", value, "projectId");
            return (Criteria) this;
        }

        public Criteria andProjectIdLessThanOrEqualTo(Integer value) {
            addCriterion("Project_id <=", value, "projectId");
            return (Criteria) this;
        }

        public Criteria andProjectIdIn(List<Integer> values) {
            addCriterion("Project_id in", values, "projectId");
            return (Criteria) this;
        }

        public Criteria andProjectIdNotIn(List<Integer> values) {
            addCriterion("Project_id not in", values, "projectId");
            return (Criteria) this;
        }

        public Criteria andProjectIdBetween(Integer value1, Integer value2) {
            addCriterion("Project_id between", value1, value2, "projectId");
            return (Criteria) this;
        }

        public Criteria andProjectIdNotBetween(Integer value1, Integer value2) {
            addCriterion("Project_id not between", value1, value2, "projectId");
            return (Criteria) this;
        }

        public Criteria andInstructorIdIsNull() {
            addCriterion("Instructor_id is null");
            return (Criteria) this;
        }

        public Criteria andInstructorIdIsNotNull() {
            addCriterion("Instructor_id is not null");
            return (Criteria) this;
        }

        public Criteria andInstructorIdEqualTo(Integer value) {
            addCriterion("Instructor_id =", value, "instructorId");
            return (Criteria) this;
        }

        public Criteria andInstructorIdNotEqualTo(Integer value) {
            addCriterion("Instructor_id <>", value, "instructorId");
            return (Criteria) this;
        }

        public Criteria andInstructorIdGreaterThan(Integer value) {
            addCriterion("Instructor_id >", value, "instructorId");
            return (Criteria) this;
        }

        public Criteria andInstructorIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("Instructor_id >=", value, "instructorId");
            return (Criteria) this;
        }

        public Criteria andInstructorIdLessThan(Integer value) {
            addCriterion("Instructor_id <", value, "instructorId");
            return (Criteria) this;
        }

        public Criteria andInstructorIdLessThanOrEqualTo(Integer value) {
            addCriterion("Instructor_id <=", value, "instructorId");
            return (Criteria) this;
        }

        public Criteria andInstructorIdIn(List<Integer> values) {
            addCriterion("Instructor_id in", values, "instructorId");
            return (Criteria) this;
        }

        public Criteria andInstructorIdNotIn(List<Integer> values) {
            addCriterion("Instructor_id not in", values, "instructorId");
            return (Criteria) this;
        }

        public Criteria andInstructorIdBetween(Integer value1, Integer value2) {
            addCriterion("Instructor_id between", value1, value2, "instructorId");
            return (Criteria) this;
        }

        public Criteria andInstructorIdNotBetween(Integer value1, Integer value2) {
            addCriterion("Instructor_id not between", value1, value2, "instructorId");
            return (Criteria) this;
        }

        public Criteria andPBeginTimeIsNull() {
            addCriterion("P_begin_time is null");
            return (Criteria) this;
        }

        public Criteria andPBeginTimeIsNotNull() {
            addCriterion("P_begin_time is not null");
            return (Criteria) this;
        }

        public Criteria andPBeginTimeEqualTo(Date value) {
            addCriterion("P_begin_time =", value, "pBeginTime");
            return (Criteria) this;
        }

        public Criteria andPBeginTimeNotEqualTo(Date value) {
            addCriterion("P_begin_time <>", value, "pBeginTime");
            return (Criteria) this;
        }

        public Criteria andPBeginTimeGreaterThan(Date value) {
            addCriterion("P_begin_time >", value, "pBeginTime");
            return (Criteria) this;
        }

        public Criteria andPBeginTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("P_begin_time >=", value, "pBeginTime");
            return (Criteria) this;
        }

        public Criteria andPBeginTimeLessThan(Date value) {
            addCriterion("P_begin_time <", value, "pBeginTime");
            return (Criteria) this;
        }

        public Criteria andPBeginTimeLessThanOrEqualTo(Date value) {
            addCriterion("P_begin_time <=", value, "pBeginTime");
            return (Criteria) this;
        }

        public Criteria andPBeginTimeIn(List<Date> values) {
            addCriterion("P_begin_time in", values, "pBeginTime");
            return (Criteria) this;
        }

        public Criteria andPBeginTimeNotIn(List<Date> values) {
            addCriterion("P_begin_time not in", values, "pBeginTime");
            return (Criteria) this;
        }

        public Criteria andPBeginTimeBetween(Date value1, Date value2) {
            addCriterion("P_begin_time between", value1, value2, "pBeginTime");
            return (Criteria) this;
        }

        public Criteria andPBeginTimeNotBetween(Date value1, Date value2) {
            addCriterion("P_begin_time not between", value1, value2, "pBeginTime");
            return (Criteria) this;
        }

        public Criteria andPEndTimeIsNull() {
            addCriterion("P_end_time is null");
            return (Criteria) this;
        }

        public Criteria andPEndTimeIsNotNull() {
            addCriterion("P_end_time is not null");
            return (Criteria) this;
        }

        public Criteria andPEndTimeEqualTo(Date value) {
            addCriterion("P_end_time =", value, "pEndTime");
            return (Criteria) this;
        }

        public Criteria andPEndTimeNotEqualTo(Date value) {
            addCriterion("P_end_time <>", value, "pEndTime");
            return (Criteria) this;
        }

        public Criteria andPEndTimeGreaterThan(Date value) {
            addCriterion("P_end_time >", value, "pEndTime");
            return (Criteria) this;
        }

        public Criteria andPEndTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("P_end_time >=", value, "pEndTime");
            return (Criteria) this;
        }

        public Criteria andPEndTimeLessThan(Date value) {
            addCriterion("P_end_time <", value, "pEndTime");
            return (Criteria) this;
        }

        public Criteria andPEndTimeLessThanOrEqualTo(Date value) {
            addCriterion("P_end_time <=", value, "pEndTime");
            return (Criteria) this;
        }

        public Criteria andPEndTimeIn(List<Date> values) {
            addCriterion("P_end_time in", values, "pEndTime");
            return (Criteria) this;
        }

        public Criteria andPEndTimeNotIn(List<Date> values) {
            addCriterion("P_end_time not in", values, "pEndTime");
            return (Criteria) this;
        }

        public Criteria andPEndTimeBetween(Date value1, Date value2) {
            addCriterion("P_end_time between", value1, value2, "pEndTime");
            return (Criteria) this;
        }

        public Criteria andPEndTimeNotBetween(Date value1, Date value2) {
            addCriterion("P_end_time not between", value1, value2, "pEndTime");
            return (Criteria) this;
        }

        public Criteria andGradeIsNull() {
            addCriterion("Grade is null");
            return (Criteria) this;
        }

        public Criteria andGradeIsNotNull() {
            addCriterion("Grade is not null");
            return (Criteria) this;
        }

        public Criteria andGradeEqualTo(Float value) {
            addCriterion("Grade =", value, "grade");
            return (Criteria) this;
        }

        public Criteria andGradeNotEqualTo(Float value) {
            addCriterion("Grade <>", value, "grade");
            return (Criteria) this;
        }

        public Criteria andGradeGreaterThan(Float value) {
            addCriterion("Grade >", value, "grade");
            return (Criteria) this;
        }

        public Criteria andGradeGreaterThanOrEqualTo(Float value) {
            addCriterion("Grade >=", value, "grade");
            return (Criteria) this;
        }

        public Criteria andGradeLessThan(Float value) {
            addCriterion("Grade <", value, "grade");
            return (Criteria) this;
        }

        public Criteria andGradeLessThanOrEqualTo(Float value) {
            addCriterion("Grade <=", value, "grade");
            return (Criteria) this;
        }

        public Criteria andGradeIn(List<Float> values) {
            addCriterion("Grade in", values, "grade");
            return (Criteria) this;
        }

        public Criteria andGradeNotIn(List<Float> values) {
            addCriterion("Grade not in", values, "grade");
            return (Criteria) this;
        }

        public Criteria andGradeBetween(Float value1, Float value2) {
            addCriterion("Grade between", value1, value2, "grade");
            return (Criteria) this;
        }

        public Criteria andGradeNotBetween(Float value1, Float value2) {
            addCriterion("Grade not between", value1, value2, "grade");
            return (Criteria) this;
        }

        public Criteria andPTitleIsNull() {
            addCriterion("P_title is null");
            return (Criteria) this;
        }

        public Criteria andPTitleIsNotNull() {
            addCriterion("P_title is not null");
            return (Criteria) this;
        }

        public Criteria andPTitleEqualTo(String value) {
            addCriterion("P_title =", value, "pTitle");
            return (Criteria) this;
        }

        public Criteria andPTitleNotEqualTo(String value) {
            addCriterion("P_title <>", value, "pTitle");
            return (Criteria) this;
        }

        public Criteria andPTitleGreaterThan(String value) {
            addCriterion("P_title >", value, "pTitle");
            return (Criteria) this;
        }

        public Criteria andPTitleGreaterThanOrEqualTo(String value) {
            addCriterion("P_title >=", value, "pTitle");
            return (Criteria) this;
        }

        public Criteria andPTitleLessThan(String value) {
            addCriterion("P_title <", value, "pTitle");
            return (Criteria) this;
        }

        public Criteria andPTitleLessThanOrEqualTo(String value) {
            addCriterion("P_title <=", value, "pTitle");
            return (Criteria) this;
        }

        public Criteria andPTitleLike(String value) {
            addCriterion("P_title like", value, "pTitle");
            return (Criteria) this;
        }

        public Criteria andPTitleNotLike(String value) {
            addCriterion("P_title not like", value, "pTitle");
            return (Criteria) this;
        }

        public Criteria andPTitleIn(List<String> values) {
            addCriterion("P_title in", values, "pTitle");
            return (Criteria) this;
        }

        public Criteria andPTitleNotIn(List<String> values) {
            addCriterion("P_title not in", values, "pTitle");
            return (Criteria) this;
        }

        public Criteria andPTitleBetween(String value1, String value2) {
            addCriterion("P_title between", value1, value2, "pTitle");
            return (Criteria) this;
        }

        public Criteria andPTitleNotBetween(String value1, String value2) {
            addCriterion("P_title not between", value1, value2, "pTitle");
            return (Criteria) this;
        }

        public Criteria andPDescriptionIsNull() {
            addCriterion("P_description is null");
            return (Criteria) this;
        }

        public Criteria andPDescriptionIsNotNull() {
            addCriterion("P_description is not null");
            return (Criteria) this;
        }

        public Criteria andPDescriptionEqualTo(String value) {
            addCriterion("P_description =", value, "pDescription");
            return (Criteria) this;
        }

        public Criteria andPDescriptionNotEqualTo(String value) {
            addCriterion("P_description <>", value, "pDescription");
            return (Criteria) this;
        }

        public Criteria andPDescriptionGreaterThan(String value) {
            addCriterion("P_description >", value, "pDescription");
            return (Criteria) this;
        }

        public Criteria andPDescriptionGreaterThanOrEqualTo(String value) {
            addCriterion("P_description >=", value, "pDescription");
            return (Criteria) this;
        }

        public Criteria andPDescriptionLessThan(String value) {
            addCriterion("P_description <", value, "pDescription");
            return (Criteria) this;
        }

        public Criteria andPDescriptionLessThanOrEqualTo(String value) {
            addCriterion("P_description <=", value, "pDescription");
            return (Criteria) this;
        }

        public Criteria andPDescriptionLike(String value) {
            addCriterion("P_description like", value, "pDescription");
            return (Criteria) this;
        }

        public Criteria andPDescriptionNotLike(String value) {
            addCriterion("P_description not like", value, "pDescription");
            return (Criteria) this;
        }

        public Criteria andPDescriptionIn(List<String> values) {
            addCriterion("P_description in", values, "pDescription");
            return (Criteria) this;
        }

        public Criteria andPDescriptionNotIn(List<String> values) {
            addCriterion("P_description not in", values, "pDescription");
            return (Criteria) this;
        }

        public Criteria andPDescriptionBetween(String value1, String value2) {
            addCriterion("P_description between", value1, value2, "pDescription");
            return (Criteria) this;
        }

        public Criteria andPDescriptionNotBetween(String value1, String value2) {
            addCriterion("P_description not between", value1, value2, "pDescription");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table project
     *
     * @mbggenerated do_not_delete_during_merge Mon Mar 05 16:40:23 CST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table project
     *
     * @mbggenerated Mon Mar 05 16:40:23 CST 2018
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}