package com.ec.entity;

public class Student {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.Student_id
     *
     * @mbggenerated Sun Mar 04 22:53:42 CST 2018
     */
    private Integer studentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.Name
     *
     * @mbggenerated Sun Mar 04 22:53:42 CST 2018
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.Password
     *
     * @mbggenerated Sun Mar 04 22:53:42 CST 2018
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.Email_add
     *
     * @mbggenerated Sun Mar 04 22:53:42 CST 2018
     */
    private String emailAdd;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.Student_id
     *
     * @return the value of student.Student_id
     *
     * @mbggenerated Sun Mar 04 22:53:42 CST 2018
     */
    public Integer getStudentId() {
        return studentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.Student_id
     *
     * @param studentId the value for student.Student_id
     *
     * @mbggenerated Sun Mar 04 22:53:42 CST 2018
     */
    public void setStudentId(Integer studentId) {
        this.studentId = studentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.Name
     *
     * @return the value of student.Name
     *
     * @mbggenerated Sun Mar 04 22:53:42 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.Name
     *
     * @param name the value for student.Name
     *
     * @mbggenerated Sun Mar 04 22:53:42 CST 2018
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.Password
     *
     * @return the value of student.Password
     *
     * @mbggenerated Sun Mar 04 22:53:42 CST 2018
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.Password
     *
     * @param password the value for student.Password
     *
     * @mbggenerated Sun Mar 04 22:53:42 CST 2018
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.Email_add
     *
     * @return the value of student.Email_add
     *
     * @mbggenerated Sun Mar 04 22:53:42 CST 2018
     */
    public String getEmailAdd() {
        return emailAdd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.Email_add
     *
     * @param emailAdd the value for student.Email_add
     *
     * @mbggenerated Sun Mar 04 22:53:42 CST 2018
     */
    public void setEmailAdd(String emailAdd) {
        this.emailAdd = emailAdd;
    }
}