package com.ec.entity;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class TaskExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table task
     *
     * @mbggenerated Sun Mar 04 22:53:42 CST 2018
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table task
     *
     * @mbggenerated Sun Mar 04 22:53:42 CST 2018
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table task
     *
     * @mbggenerated Sun Mar 04 22:53:42 CST 2018
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task
     *
     * @mbggenerated Sun Mar 04 22:53:42 CST 2018
     */
    public TaskExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task
     *
     * @mbggenerated Sun Mar 04 22:53:42 CST 2018
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task
     *
     * @mbggenerated Sun Mar 04 22:53:42 CST 2018
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task
     *
     * @mbggenerated Sun Mar 04 22:53:42 CST 2018
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task
     *
     * @mbggenerated Sun Mar 04 22:53:42 CST 2018
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task
     *
     * @mbggenerated Sun Mar 04 22:53:42 CST 2018
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task
     *
     * @mbggenerated Sun Mar 04 22:53:42 CST 2018
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task
     *
     * @mbggenerated Sun Mar 04 22:53:42 CST 2018
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task
     *
     * @mbggenerated Sun Mar 04 22:53:42 CST 2018
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task
     *
     * @mbggenerated Sun Mar 04 22:53:42 CST 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task
     *
     * @mbggenerated Sun Mar 04 22:53:42 CST 2018
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table task
     *
     * @mbggenerated Sun Mar 04 22:53:42 CST 2018
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andTaskIdIsNull() {
            addCriterion("Task_id is null");
            return (Criteria) this;
        }

        public Criteria andTaskIdIsNotNull() {
            addCriterion("Task_id is not null");
            return (Criteria) this;
        }

        public Criteria andTaskIdEqualTo(Integer value) {
            addCriterion("Task_id =", value, "taskId");
            return (Criteria) this;
        }

        public Criteria andTaskIdNotEqualTo(Integer value) {
            addCriterion("Task_id <>", value, "taskId");
            return (Criteria) this;
        }

        public Criteria andTaskIdGreaterThan(Integer value) {
            addCriterion("Task_id >", value, "taskId");
            return (Criteria) this;
        }

        public Criteria andTaskIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("Task_id >=", value, "taskId");
            return (Criteria) this;
        }

        public Criteria andTaskIdLessThan(Integer value) {
            addCriterion("Task_id <", value, "taskId");
            return (Criteria) this;
        }

        public Criteria andTaskIdLessThanOrEqualTo(Integer value) {
            addCriterion("Task_id <=", value, "taskId");
            return (Criteria) this;
        }

        public Criteria andTaskIdIn(List<Integer> values) {
            addCriterion("Task_id in", values, "taskId");
            return (Criteria) this;
        }

        public Criteria andTaskIdNotIn(List<Integer> values) {
            addCriterion("Task_id not in", values, "taskId");
            return (Criteria) this;
        }

        public Criteria andTaskIdBetween(Integer value1, Integer value2) {
            addCriterion("Task_id between", value1, value2, "taskId");
            return (Criteria) this;
        }

        public Criteria andTaskIdNotBetween(Integer value1, Integer value2) {
            addCriterion("Task_id not between", value1, value2, "taskId");
            return (Criteria) this;
        }

        public Criteria andStudentIdIsNull() {
            addCriterion("Student_id is null");
            return (Criteria) this;
        }

        public Criteria andStudentIdIsNotNull() {
            addCriterion("Student_id is not null");
            return (Criteria) this;
        }

        public Criteria andStudentIdEqualTo(Integer value) {
            addCriterion("Student_id =", value, "studentId");
            return (Criteria) this;
        }

        public Criteria andStudentIdNotEqualTo(Integer value) {
            addCriterion("Student_id <>", value, "studentId");
            return (Criteria) this;
        }

        public Criteria andStudentIdGreaterThan(Integer value) {
            addCriterion("Student_id >", value, "studentId");
            return (Criteria) this;
        }

        public Criteria andStudentIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("Student_id >=", value, "studentId");
            return (Criteria) this;
        }

        public Criteria andStudentIdLessThan(Integer value) {
            addCriterion("Student_id <", value, "studentId");
            return (Criteria) this;
        }

        public Criteria andStudentIdLessThanOrEqualTo(Integer value) {
            addCriterion("Student_id <=", value, "studentId");
            return (Criteria) this;
        }

        public Criteria andStudentIdIn(List<Integer> values) {
            addCriterion("Student_id in", values, "studentId");
            return (Criteria) this;
        }

        public Criteria andStudentIdNotIn(List<Integer> values) {
            addCriterion("Student_id not in", values, "studentId");
            return (Criteria) this;
        }

        public Criteria andStudentIdBetween(Integer value1, Integer value2) {
            addCriterion("Student_id between", value1, value2, "studentId");
            return (Criteria) this;
        }

        public Criteria andStudentIdNotBetween(Integer value1, Integer value2) {
            addCriterion("Student_id not between", value1, value2, "studentId");
            return (Criteria) this;
        }

        public Criteria andProjectIdIsNull() {
            addCriterion("Project_id is null");
            return (Criteria) this;
        }

        public Criteria andProjectIdIsNotNull() {
            addCriterion("Project_id is not null");
            return (Criteria) this;
        }

        public Criteria andProjectIdEqualTo(Integer value) {
            addCriterion("Project_id =", value, "projectId");
            return (Criteria) this;
        }

        public Criteria andProjectIdNotEqualTo(Integer value) {
            addCriterion("Project_id <>", value, "projectId");
            return (Criteria) this;
        }

        public Criteria andProjectIdGreaterThan(Integer value) {
            addCriterion("Project_id >", value, "projectId");
            return (Criteria) this;
        }

        public Criteria andProjectIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("Project_id >=", value, "projectId");
            return (Criteria) this;
        }

        public Criteria andProjectIdLessThan(Integer value) {
            addCriterion("Project_id <", value, "projectId");
            return (Criteria) this;
        }

        public Criteria andProjectIdLessThanOrEqualTo(Integer value) {
            addCriterion("Project_id <=", value, "projectId");
            return (Criteria) this;
        }

        public Criteria andProjectIdIn(List<Integer> values) {
            addCriterion("Project_id in", values, "projectId");
            return (Criteria) this;
        }

        public Criteria andProjectIdNotIn(List<Integer> values) {
            addCriterion("Project_id not in", values, "projectId");
            return (Criteria) this;
        }

        public Criteria andProjectIdBetween(Integer value1, Integer value2) {
            addCriterion("Project_id between", value1, value2, "projectId");
            return (Criteria) this;
        }

        public Criteria andProjectIdNotBetween(Integer value1, Integer value2) {
            addCriterion("Project_id not between", value1, value2, "projectId");
            return (Criteria) this;
        }

        public Criteria andPhaseIdIsNull() {
            addCriterion("Phase_id is null");
            return (Criteria) this;
        }

        public Criteria andPhaseIdIsNotNull() {
            addCriterion("Phase_id is not null");
            return (Criteria) this;
        }

        public Criteria andPhaseIdEqualTo(Integer value) {
            addCriterion("Phase_id =", value, "phaseId");
            return (Criteria) this;
        }

        public Criteria andPhaseIdNotEqualTo(Integer value) {
            addCriterion("Phase_id <>", value, "phaseId");
            return (Criteria) this;
        }

        public Criteria andPhaseIdGreaterThan(Integer value) {
            addCriterion("Phase_id >", value, "phaseId");
            return (Criteria) this;
        }

        public Criteria andPhaseIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("Phase_id >=", value, "phaseId");
            return (Criteria) this;
        }

        public Criteria andPhaseIdLessThan(Integer value) {
            addCriterion("Phase_id <", value, "phaseId");
            return (Criteria) this;
        }

        public Criteria andPhaseIdLessThanOrEqualTo(Integer value) {
            addCriterion("Phase_id <=", value, "phaseId");
            return (Criteria) this;
        }

        public Criteria andPhaseIdIn(List<Integer> values) {
            addCriterion("Phase_id in", values, "phaseId");
            return (Criteria) this;
        }

        public Criteria andPhaseIdNotIn(List<Integer> values) {
            addCriterion("Phase_id not in", values, "phaseId");
            return (Criteria) this;
        }

        public Criteria andPhaseIdBetween(Integer value1, Integer value2) {
            addCriterion("Phase_id between", value1, value2, "phaseId");
            return (Criteria) this;
        }

        public Criteria andPhaseIdNotBetween(Integer value1, Integer value2) {
            addCriterion("Phase_id not between", value1, value2, "phaseId");
            return (Criteria) this;
        }

        public Criteria andWorkloadIsNull() {
            addCriterion("Workload is null");
            return (Criteria) this;
        }

        public Criteria andWorkloadIsNotNull() {
            addCriterion("Workload is not null");
            return (Criteria) this;
        }

        public Criteria andWorkloadEqualTo(Integer value) {
            addCriterion("Workload =", value, "workload");
            return (Criteria) this;
        }

        public Criteria andWorkloadNotEqualTo(Integer value) {
            addCriterion("Workload <>", value, "workload");
            return (Criteria) this;
        }

        public Criteria andWorkloadGreaterThan(Integer value) {
            addCriterion("Workload >", value, "workload");
            return (Criteria) this;
        }

        public Criteria andWorkloadGreaterThanOrEqualTo(Integer value) {
            addCriterion("Workload >=", value, "workload");
            return (Criteria) this;
        }

        public Criteria andWorkloadLessThan(Integer value) {
            addCriterion("Workload <", value, "workload");
            return (Criteria) this;
        }

        public Criteria andWorkloadLessThanOrEqualTo(Integer value) {
            addCriterion("Workload <=", value, "workload");
            return (Criteria) this;
        }

        public Criteria andWorkloadIn(List<Integer> values) {
            addCriterion("Workload in", values, "workload");
            return (Criteria) this;
        }

        public Criteria andWorkloadNotIn(List<Integer> values) {
            addCriterion("Workload not in", values, "workload");
            return (Criteria) this;
        }

        public Criteria andWorkloadBetween(Integer value1, Integer value2) {
            addCriterion("Workload between", value1, value2, "workload");
            return (Criteria) this;
        }

        public Criteria andWorkloadNotBetween(Integer value1, Integer value2) {
            addCriterion("Workload not between", value1, value2, "workload");
            return (Criteria) this;
        }

        public Criteria andTBeginTimeIsNull() {
            addCriterion("T_begin_time is null");
            return (Criteria) this;
        }

        public Criteria andTBeginTimeIsNotNull() {
            addCriterion("T_begin_time is not null");
            return (Criteria) this;
        }

        public Criteria andTBeginTimeEqualTo(Date value) {
            addCriterion("T_begin_time =", value, "tBeginTime");
            return (Criteria) this;
        }

        public Criteria andTBeginTimeNotEqualTo(Date value) {
            addCriterion("T_begin_time <>", value, "tBeginTime");
            return (Criteria) this;
        }

        public Criteria andTBeginTimeGreaterThan(Date value) {
            addCriterion("T_begin_time >", value, "tBeginTime");
            return (Criteria) this;
        }

        public Criteria andTBeginTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("T_begin_time >=", value, "tBeginTime");
            return (Criteria) this;
        }

        public Criteria andTBeginTimeLessThan(Date value) {
            addCriterion("T_begin_time <", value, "tBeginTime");
            return (Criteria) this;
        }

        public Criteria andTBeginTimeLessThanOrEqualTo(Date value) {
            addCriterion("T_begin_time <=", value, "tBeginTime");
            return (Criteria) this;
        }

        public Criteria andTBeginTimeIn(List<Date> values) {
            addCriterion("T_begin_time in", values, "tBeginTime");
            return (Criteria) this;
        }

        public Criteria andTBeginTimeNotIn(List<Date> values) {
            addCriterion("T_begin_time not in", values, "tBeginTime");
            return (Criteria) this;
        }

        public Criteria andTBeginTimeBetween(Date value1, Date value2) {
            addCriterion("T_begin_time between", value1, value2, "tBeginTime");
            return (Criteria) this;
        }

        public Criteria andTBeginTimeNotBetween(Date value1, Date value2) {
            addCriterion("T_begin_time not between", value1, value2, "tBeginTime");
            return (Criteria) this;
        }

        public Criteria andTEndTimeIsNull() {
            addCriterion("T_end_time is null");
            return (Criteria) this;
        }

        public Criteria andTEndTimeIsNotNull() {
            addCriterion("T_end_time is not null");
            return (Criteria) this;
        }

        public Criteria andTEndTimeEqualTo(Date value) {
            addCriterion("T_end_time =", value, "tEndTime");
            return (Criteria) this;
        }

        public Criteria andTEndTimeNotEqualTo(Date value) {
            addCriterion("T_end_time <>", value, "tEndTime");
            return (Criteria) this;
        }

        public Criteria andTEndTimeGreaterThan(Date value) {
            addCriterion("T_end_time >", value, "tEndTime");
            return (Criteria) this;
        }

        public Criteria andTEndTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("T_end_time >=", value, "tEndTime");
            return (Criteria) this;
        }

        public Criteria andTEndTimeLessThan(Date value) {
            addCriterion("T_end_time <", value, "tEndTime");
            return (Criteria) this;
        }

        public Criteria andTEndTimeLessThanOrEqualTo(Date value) {
            addCriterion("T_end_time <=", value, "tEndTime");
            return (Criteria) this;
        }

        public Criteria andTEndTimeIn(List<Date> values) {
            addCriterion("T_end_time in", values, "tEndTime");
            return (Criteria) this;
        }

        public Criteria andTEndTimeNotIn(List<Date> values) {
            addCriterion("T_end_time not in", values, "tEndTime");
            return (Criteria) this;
        }

        public Criteria andTEndTimeBetween(Date value1, Date value2) {
            addCriterion("T_end_time between", value1, value2, "tEndTime");
            return (Criteria) this;
        }

        public Criteria andTEndTimeNotBetween(Date value1, Date value2) {
            addCriterion("T_end_time not between", value1, value2, "tEndTime");
            return (Criteria) this;
        }

        public Criteria andStatusIsNull() {
            addCriterion("status is null");
            return (Criteria) this;
        }

        public Criteria andStatusIsNotNull() {
            addCriterion("status is not null");
            return (Criteria) this;
        }

        public Criteria andStatusEqualTo(Boolean value) {
            addCriterion("status =", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotEqualTo(Boolean value) {
            addCriterion("status <>", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThan(Boolean value) {
            addCriterion("status >", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThanOrEqualTo(Boolean value) {
            addCriterion("status >=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThan(Boolean value) {
            addCriterion("status <", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThanOrEqualTo(Boolean value) {
            addCriterion("status <=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusIn(List<Boolean> values) {
            addCriterion("status in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotIn(List<Boolean> values) {
            addCriterion("status not in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusBetween(Boolean value1, Boolean value2) {
            addCriterion("status between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotBetween(Boolean value1, Boolean value2) {
            addCriterion("status not between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andTTitleIsNull() {
            addCriterion("T_title is null");
            return (Criteria) this;
        }

        public Criteria andTTitleIsNotNull() {
            addCriterion("T_title is not null");
            return (Criteria) this;
        }

        public Criteria andTTitleEqualTo(String value) {
            addCriterion("T_title =", value, "tTitle");
            return (Criteria) this;
        }

        public Criteria andTTitleNotEqualTo(String value) {
            addCriterion("T_title <>", value, "tTitle");
            return (Criteria) this;
        }

        public Criteria andTTitleGreaterThan(String value) {
            addCriterion("T_title >", value, "tTitle");
            return (Criteria) this;
        }

        public Criteria andTTitleGreaterThanOrEqualTo(String value) {
            addCriterion("T_title >=", value, "tTitle");
            return (Criteria) this;
        }

        public Criteria andTTitleLessThan(String value) {
            addCriterion("T_title <", value, "tTitle");
            return (Criteria) this;
        }

        public Criteria andTTitleLessThanOrEqualTo(String value) {
            addCriterion("T_title <=", value, "tTitle");
            return (Criteria) this;
        }

        public Criteria andTTitleLike(String value) {
            addCriterion("T_title like", value, "tTitle");
            return (Criteria) this;
        }

        public Criteria andTTitleNotLike(String value) {
            addCriterion("T_title not like", value, "tTitle");
            return (Criteria) this;
        }

        public Criteria andTTitleIn(List<String> values) {
            addCriterion("T_title in", values, "tTitle");
            return (Criteria) this;
        }

        public Criteria andTTitleNotIn(List<String> values) {
            addCriterion("T_title not in", values, "tTitle");
            return (Criteria) this;
        }

        public Criteria andTTitleBetween(String value1, String value2) {
            addCriterion("T_title between", value1, value2, "tTitle");
            return (Criteria) this;
        }

        public Criteria andTTitleNotBetween(String value1, String value2) {
            addCriterion("T_title not between", value1, value2, "tTitle");
            return (Criteria) this;
        }

        public Criteria andTDescriptionIsNull() {
            addCriterion("T_description is null");
            return (Criteria) this;
        }

        public Criteria andTDescriptionIsNotNull() {
            addCriterion("T_description is not null");
            return (Criteria) this;
        }

        public Criteria andTDescriptionEqualTo(String value) {
            addCriterion("T_description =", value, "tDescription");
            return (Criteria) this;
        }

        public Criteria andTDescriptionNotEqualTo(String value) {
            addCriterion("T_description <>", value, "tDescription");
            return (Criteria) this;
        }

        public Criteria andTDescriptionGreaterThan(String value) {
            addCriterion("T_description >", value, "tDescription");
            return (Criteria) this;
        }

        public Criteria andTDescriptionGreaterThanOrEqualTo(String value) {
            addCriterion("T_description >=", value, "tDescription");
            return (Criteria) this;
        }

        public Criteria andTDescriptionLessThan(String value) {
            addCriterion("T_description <", value, "tDescription");
            return (Criteria) this;
        }

        public Criteria andTDescriptionLessThanOrEqualTo(String value) {
            addCriterion("T_description <=", value, "tDescription");
            return (Criteria) this;
        }

        public Criteria andTDescriptionLike(String value) {
            addCriterion("T_description like", value, "tDescription");
            return (Criteria) this;
        }

        public Criteria andTDescriptionNotLike(String value) {
            addCriterion("T_description not like", value, "tDescription");
            return (Criteria) this;
        }

        public Criteria andTDescriptionIn(List<String> values) {
            addCriterion("T_description in", values, "tDescription");
            return (Criteria) this;
        }

        public Criteria andTDescriptionNotIn(List<String> values) {
            addCriterion("T_description not in", values, "tDescription");
            return (Criteria) this;
        }

        public Criteria andTDescriptionBetween(String value1, String value2) {
            addCriterion("T_description between", value1, value2, "tDescription");
            return (Criteria) this;
        }

        public Criteria andTDescriptionNotBetween(String value1, String value2) {
            addCriterion("T_description not between", value1, value2, "tDescription");
            return (Criteria) this;
        }

        public Criteria andDeadlineIsNull() {
            addCriterion("deadline is null");
            return (Criteria) this;
        }

        public Criteria andDeadlineIsNotNull() {
            addCriterion("deadline is not null");
            return (Criteria) this;
        }

        public Criteria andDeadlineEqualTo(Date value) {
            addCriterion("deadline =", value, "deadline");
            return (Criteria) this;
        }

        public Criteria andDeadlineNotEqualTo(Date value) {
            addCriterion("deadline <>", value, "deadline");
            return (Criteria) this;
        }

        public Criteria andDeadlineGreaterThan(Date value) {
            addCriterion("deadline >", value, "deadline");
            return (Criteria) this;
        }

        public Criteria andDeadlineGreaterThanOrEqualTo(Date value) {
            addCriterion("deadline >=", value, "deadline");
            return (Criteria) this;
        }

        public Criteria andDeadlineLessThan(Date value) {
            addCriterion("deadline <", value, "deadline");
            return (Criteria) this;
        }

        public Criteria andDeadlineLessThanOrEqualTo(Date value) {
            addCriterion("deadline <=", value, "deadline");
            return (Criteria) this;
        }

        public Criteria andDeadlineIn(List<Date> values) {
            addCriterion("deadline in", values, "deadline");
            return (Criteria) this;
        }

        public Criteria andDeadlineNotIn(List<Date> values) {
            addCriterion("deadline not in", values, "deadline");
            return (Criteria) this;
        }

        public Criteria andDeadlineBetween(Date value1, Date value2) {
            addCriterion("deadline between", value1, value2, "deadline");
            return (Criteria) this;
        }

        public Criteria andDeadlineNotBetween(Date value1, Date value2) {
            addCriterion("deadline not between", value1, value2, "deadline");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table task
     *
     * @mbggenerated do_not_delete_during_merge Sun Mar 04 22:53:42 CST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table task
     *
     * @mbggenerated Sun Mar 04 22:53:42 CST 2018
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}