package com.ec.mapper;

import com.ec.entity.Instructor;
import com.ec.entity.InstructorExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface InstructorMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table instructor
     *
     * @mbggenerated Mon Mar 05 16:40:23 CST 2018
     */
    int countByExample(InstructorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table instructor
     *
     * @mbggenerated Mon Mar 05 16:40:23 CST 2018
     */
    int deleteByExample(InstructorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table instructor
     *
     * @mbggenerated Mon Mar 05 16:40:23 CST 2018
     */
    int deleteByPrimaryKey(Integer instructorId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table instructor
     *
     * @mbggenerated Mon Mar 05 16:40:23 CST 2018
     */
    int insert(Instructor record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table instructor
     *
     * @mbggenerated Mon Mar 05 16:40:23 CST 2018
     */
    int insertSelective(Instructor record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table instructor
     *
     * @mbggenerated Mon Mar 05 16:40:23 CST 2018
     */
    List<Instructor> selectByExample(InstructorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table instructor
     *
     * @mbggenerated Mon Mar 05 16:40:23 CST 2018
     */
    Instructor selectByPrimaryKey(Integer instructorId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table instructor
     *
     * @mbggenerated Mon Mar 05 16:40:23 CST 2018
     */
    int updateByExampleSelective(@Param("record") Instructor record, @Param("example") InstructorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table instructor
     *
     * @mbggenerated Mon Mar 05 16:40:23 CST 2018
     */
    int updateByExample(@Param("record") Instructor record, @Param("example") InstructorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table instructor
     *
     * @mbggenerated Mon Mar 05 16:40:23 CST 2018
     */
    int updateByPrimaryKeySelective(Instructor record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table instructor
     *
     * @mbggenerated Mon Mar 05 16:40:23 CST 2018
     */
    int updateByPrimaryKey(Instructor record);
}