package com.ec.mapper;

import com.ec.entity.Phase;
import com.ec.entity.PhaseExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PhaseMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table phase
     *
     * @mbggenerated Sun Mar 04 18:54:24 CST 2018
     */
    int countByExample(PhaseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table phase
     *
     * @mbggenerated Sun Mar 04 18:54:24 CST 2018
     */
    int deleteByExample(PhaseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table phase
     *
     * @mbggenerated Sun Mar 04 18:54:24 CST 2018
     */
    int deleteByPrimaryKey(Integer phaseId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table phase
     *
     * @mbggenerated Sun Mar 04 18:54:24 CST 2018
     */
    int insert(Phase record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table phase
     *
     * @mbggenerated Sun Mar 04 18:54:24 CST 2018
     */
    int insertSelective(Phase record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table phase
     *
     * @mbggenerated Sun Mar 04 18:54:24 CST 2018
     */
    List<Phase> selectByExample(PhaseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table phase
     *
     * @mbggenerated Sun Mar 04 18:54:24 CST 2018
     */
    Phase selectByPrimaryKey(Integer phaseId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table phase
     *
     * @mbggenerated Sun Mar 04 18:54:24 CST 2018
     */
    int updateByExampleSelective(@Param("record") Phase record, @Param("example") PhaseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table phase
     *
     * @mbggenerated Sun Mar 04 18:54:24 CST 2018
     */
    int updateByExample(@Param("record") Phase record, @Param("example") PhaseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table phase
     *
     * @mbggenerated Sun Mar 04 18:54:24 CST 2018
     */
    int updateByPrimaryKeySelective(Phase record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table phase
     *
     * @mbggenerated Sun Mar 04 18:54:24 CST 2018
     */
    int updateByPrimaryKey(Phase record);
}